// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHEwZUn934hWrta_F_EGMiH_BZVAibXGY',
    appId: '1:471348354954:web:8e7578d6e99d2d2e30b273',
    messagingSenderId: '471348354954',
    projectId: 'smart-accident-detection-99df6',
    authDomain: 'smart-accident-detection-99df6.firebaseapp.com',
    storageBucket: 'smart-accident-detection-99df6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyYP2obsMl0WZJ5IR8T6rVjNQRl9umpN0',
    appId: '1:471348354954:android:525fb5fd2e50246e30b273',
    messagingSenderId: '471348354954',
    projectId: 'smart-accident-detection-99df6',
    storageBucket: 'smart-accident-detection-99df6.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHEwZUn934hWrta_F_EGMiH_BZVAibXGY',
    appId: '1:471348354954:web:56cfef3ef640668130b273',
    messagingSenderId: '471348354954',
    projectId: 'smart-accident-detection-99df6',
    authDomain: 'smart-accident-detection-99df6.firebaseapp.com',
    storageBucket: 'smart-accident-detection-99df6.firebasestorage.app',
  );
}
